parameters:
    evaluation_evaluation.table_data_table_name: 'i2c_table_data'
    evaluation_evaluation.table_data_command_name: 'table-data:schema:update'
    evaluation_evaluation.evaluation_table_name: 'evaluation'
    evaluation_evaluation.evaluation_command_name: 'evaluation:schema:update'
    evaluation_evaluation.chapter_table_name: 'chapter'
    evaluation_evaluation.chapter_command_name: 'chapter:schema:update'
    evaluation_evaluation.evaluation_chapters_table_name: 'evaluation_chapters'
    evaluation_evaluation.evaluation_chapters_command_name: 'evaluation-chapters:schema:update'

services:
    evaluation_evaluation.evaluation_schema_update_command:
        class: i2c\SetupBundle\Command\TableSchemaUpdateCommand
        arguments:
            - @evaluation_evaluation.evaluation_schema_update
            - %evaluation_evaluation.evaluation_command_name%
        tags:
          - { name: console.command }

    evaluation_evaluation.table_data_schema_update_command:
        class: i2c\SetupBundle\Command\TableSchemaUpdateCommand
        arguments:
            - @evaluation_evaluation.table_data_schema_update
            - %evaluation_evaluation.table_data_command_name%
        tags:
          - { name: console.command }

    evaluation_evaluation.chapter_schema_update_command:
        class: i2c\SetupBundle\Command\TableSchemaUpdateCommand
        arguments:
            - @evaluation_evaluation.chapter_schema_update
            - %evaluation_evaluation.chapter_command_name%
        tags:
          - { name: console.command }

    evaluation_evaluation.evaluation_chapters_schema_update_command:
        class: i2c\SetupBundle\Command\TableSchemaUpdateCommand
        arguments:
            - @evaluation_evaluation.evaluation_chapters_schema_update
            - %evaluation_evaluation.evaluation_chapters_command_name%
        tags:
          - { name: console.command }

    evaluation_evaluation.evaluation_schema_update:
        class: Evaluation\EvaluationBundle\Services\EvaluationSchemaUpdate
        arguments: [@doctrine, %evaluation_evaluation.evaluation_table_name% ]

    evaluation_evaluation.table_data_schema_update:
        class: Evaluation\EvaluationBundle\Services\TableDataSchemaUpdateService
        arguments: [@doctrine, %evaluation_evaluation.table_data_table_name% ]

    evaluation_evaluation.chapter_schema_update:
        class: Evaluation\EvaluationBundle\Services\ChapterSchemaUpdate
        arguments: [@doctrine, %evaluation_evaluation.chapter_table_name% ]

    evaluation_evaluation.evaluation_chapters_schema_update:
        class: Evaluation\EvaluationBundle\Services\EvaluationChaptersSchemaUpdate
        arguments: [@doctrine, %evaluation_evaluation.evaluation_chapters_table_name% ]

    evaluation_evaluation.chapters_service:
        class: Evaluation\EvaluationBundle\Services\Chapter
        arguments: [@serializer, @doctrine]

    evaluation_evaluation.evaluation_service:
        class: Evaluation\EvaluationBundle\Services\Evaluation
        arguments: [@serializer, @doctrine]

    evaluation_evaluation.evaluation_database_manager_service:
        class: Evaluation\EvaluationBundle\Services\EvaluationDataBaseManager
        arguments: [@oro_security.acl_helper, @doctrine]

    evaluation_evaluation.table_data_database_manager_service:
        class: Evaluation\EvaluationBundle\Services\TableDataDatabaseManager
        arguments: [@doctrine]

    evaluation_evaluation.evaluation_jms_post_serializer:
        class: Evaluation\EvaluationBundle\EventListener\EvaluationPostSerializeListener
        tags:
            - { name: jms_serializer.event_subscriber, event: serializer.post_serialize }
