services:
    evaluation_evaluation.chapters_service:
        class: Evaluation\EvaluationBundle\Services\Chapter
        arguments: [@serializer, @doctrine]

    evaluation_evaluation.evaluation_service:
        class: Evaluation\EvaluationBundle\Services\Evaluation
        arguments: [@serializer, @doctrine]

    evaluation_evaluation.evaluation_database_manager_service:
        class: Evaluation\EvaluationBundle\Services\EvaluationDataBaseManager
        arguments: [@oro_security.acl_helper, @doctrine]

    evaluation_evaluation.table_data_database_manager_service:
        class: Evaluation\EvaluationBundle\Services\TableDataDatabaseManager
        arguments: [@doctrine]

    evaluation_evaluation.evaluation_jms_post_serializer:
        class: Evaluation\EvaluationBundle\EventListener\EvaluationPostSerializeListener
        tags:
            - { name: jms_serializer.event_subscriber, event: serializer.post_serialize }
