oro_menu_config:
    items:
        activities_tab:
            display: false
            displayChildren: false
        reports_tab:
            display: false
            displayChildren: false
        dashboard_tab:
            display: false
            displayChildren: false
        oro_notification_emailnotification_list:
            display: false
            displayChildren: false
        oro_business_unit_list:
            label: 'Suppliers'
            route: 'oro_business_unit_index'
            extras:
                description: 'oro.business_unit.menu.list.description'
        system_tab:
            display: true
            displayChildren: true
        dashboard_view:
            label: 'oro.dashboard.menu.dashboards_tab.label'
            uri: '/'
            linkAttributes:
                class: 'no-hash'
            attributes:
                class: 'no-hash'

    tree:
        application_menu:
            children:
                dashboard_view: ~
                user_list: ~
                oro_business_unit_list: ~
                system_tab: ~