#
#  - name: Install Apache
##    command: yum install --quiet -y httpd httpd-devel
#    yum: name={{ item }} state=present
#    with_items:
#    - httpd
#    - httpd-devel
#
##  - name: Copy Oro config file
##    copy:
##      src: "{{ item.src }}"
##      dest: "{{ item.dest }}"
##      owner: root
##      group: root
##      mode: 644
##    with_items:
##    - {
##      src: "/path/to/config/httpd.conf"
##      dest: "/etc/httpd/conf/httpd.conf"
##    }
#
#  - name: Start Apache and configure it to run at boot
#    service: name=httpd state=started enabled=yes

- name: set SELinux to permissive
  action: selinux policy=targeted state=permissive

- name: Check if Oro Platform is installed.
  stat: "path=/home/vagrant/sync/backend/composer.lock"
  register: composer_locked

- name: Debug composer_locked
  debug: msg="Variable 'composer_locked' is set to {{ composer_locked }}"

- name: Upgrade dependencies
  shell: >
    cd /var/www/html/backend && composer update
  when: composer_locked.stat.exists

- name: Copy vhost
  template: src=i2ces.conf.j2 dest=/etc/httpd/conf.d/i2ces.conf mode=0644
  notify: restart apache

- name: Install node
  shell: >
    sudo yum -y install npm
    creates: /usr/bin/node

- name: Check if uploads folder exists.
  stat: "path=/var/www/html/web/uploads"
  register: uploads_exists

- name: Create uploads folder.
  command: "mkdir /var/www/html/web/uploads"
  when: not uploads_exists.stat.exists

- name: Fetch Oro Platform
  command: " {{item}} "
  with_items:
    - /usr/local/bin/composer install -d /var/www/html -n
    - chmod 777 /var/www/html/web/uploads
    - sudo chmod 777 /var/www/html/app/logs
    - sudo chmod 777 /var/www/html/app/attachment
    - sudo chmod 777 /var/www/html/app/config/parameters.yml
    - sudo chmod -R 777 /var/www/html/app/cache
    - sudo chmod -R 777 /var/www/html/app/logs
    - sudo chmod -R 777 /var/www/html/web/bundles/
    - mysql -uroot -proot -e "create database IF NOT EXISTS bap_standard"
- set_fact: colon=":"

- name: Update ORO db pass
  lineinfile: dest=/var/www/html/app/config/parameters.yml regexp='(database_password:\ null)' line="    database_password{{colon}} root"

- name: Install Oro Platform
  command: chdir=/var/www/html php ./app/console oro:install --application-url i2ces.dev --organization-name i2c --user-name user --user-email gb@tekkie.us --user-firstname first --user-lastname last --user-password pass --drop-database --sample-data no --force -n
