
- name: set SELinux to permissive
  action: selinux policy=targeted state=permissive

- name: Check if Oro Platform is installed.
  stat: "path=/var/www/html/composer.lock"
  register: composer_locked

- name: Debug composer_locked
  debug: msg="Variable 'composer_locked' is set to {{ composer_locked }}"

- name: Upgrade dependencies
  command: " {{ item }} "
  with_items:
    - /usr/local/bin/composer update -d /var/www/html -n --prefer-dist --no-scripts
  when: composer_locked.stat.exists

- name: Copy vhost
  template: src=i2ces.conf.j2 dest=/etc/httpd/conf.d/i2ces.conf mode=0644
  notify: restart apache

- name: Install node
  shell: >
    sudo yum -y install npm
    creates: /usr/bin/node

- name: Check if web/uploads folder exists.
  stat: "path=/var/www/html/web/uploads"
  register: uploads_exists

- name: Create web/uploads folder.
  command: "mkdir /var/www/html/web/uploads"
  when: not uploads_exists.stat.exists

- name: Check if web/bundles folder exists.
  stat: "path=/var/www/html/web/bundles"
  register: bundles_exists

- name: Create web/bundles folder.
  command: "mkdir /var/www/html/web/bundles"
  when: not bundles_exists.stat.exists

- name: Maxxed out composer timeout
  shell: >
    export COMPOSER_PROCESS_TIMEOUT=3000

- name: Fetch Oro Platform
  command: " {{item}} "
  with_items:
    - /usr/local/bin/composer install -d /var/www/html -n --prefer-dist --no-scripts

- name: New Parameters.yml
  template: src=parameters.yml dest=/var/www/html/app/config/parameters.yml

- name: Install and set permissions
  command: " {{item}} "
  with_items:
    - /usr/local/bin/composer install -d /var/www/html -n --prefer-dist
    - chmod 777 /var/www/html/web/uploads
    - sudo chmod 777 /var/www/html/app/logs
    - sudo chmod 777 /var/www/html/app/attachment
    - sudo chmod 777 /var/www/html/app/config/parameters.yml
    - sudo chmod -R 777 /var/www/html/app/cache
    - sudo chmod -R 777 /var/www/html/app/logs
    - sudo chmod -R 777 /var/www/html/web/bundles/
    - mysql -uroot -proot -e "create database IF NOT EXISTS i2c"
- set_fact: colon=":"

- name: Update ORO db pass
  lineinfile: dest=/var/www/html/app/config/parameters.yml regexp='(database_password:\ null)' line="    database_password{{colon}} root"

- name: Install Oro Platform
  command: chdir=/var/www/html php ./app/console oro:install --application-url i2ces.dev --organization-name i2c --user-name user --user-email gb@tekkie.us --user-firstname first --user-lastname last --user-password pass --drop-database --sample-data no --force -n
