parameters:
    initial_setup_config:
        roles:
            supplier:
                name: Supplier
                identifier: ROLE_SUPPLIER
                access:
                    oid: 'Entity:EvaluationEvaluationBundle:Evaluation'
                    permissions: [64] # EntityMaskBuilder::MASK_VIEW_LOCAL
            employee:
                name: i2c Employee
                identifier: ROLE_EMPLOYEE
                access:
                    oid: 'Entity:EvaluationEvaluationBundle:Evaluation'
                    permissions: [64, 256] # EntityMaskBuilder::MASK_VIEW_LOCAL, EntityMaskBuilder::MASK_EDIT_LOCAL
        suppliers:
            dummy_one:
                name: Dummy Supplier One
                email: dummy-one@email.none
                fax: some fax
                phone: XXXXXXXXXXXXXXXX
                website: http://dummy-one.none
            dummy_two:
                name: Dummy Supplier Two
                email: dummy-two@email.none
                fax: some other fax
                phone: XXXXXXXXXXXXXXXX
                website: http://dummy-two.none

services:
    evaluation_setup.initial_setup_command:
        class: Evaluation\SetupBundle\Command\InitialSetupCommand
        arguments: [%initial_setup_config%]
        tags:
          - { name: console.command }

    evaluation_setup.schema_update_command:
        class: Evaluation\SetupBundle\Command\DatabaseSchemaUpdateCommand
        arguments: [@evaluation_setup.schema_update_container]
        tags:
          - { name: console.command }

    evaluation_setup.schema_update_container:
        class: Evaluation\SetupBundle\Services\SchemaUpdateContainer
        calls:
          - [ addSchemaUpdateService, [@evaluation_evaluation.evaluation_schema_update] ]
          - [ addSchemaUpdateService, [@evaluation_evaluation.medium_schema_update] ]
          - [ addSchemaUpdateService, [@evaluation_evaluation.evaluation_mediums_schema_update] ]
          - [ addSchemaUpdateService, [@evaluation_evaluation.chapter_schema_update] ]
          - [ addSchemaUpdateService, [@evaluation_evaluation.evaluation_chapters_schema_update] ]
