services:
    i2c_generate_evaluation.chapter_diagram.campaign_background:
        class: i2c\GenerateEvaluationBundle\Services\ChartDataSetConfig\CampaignBackground

    i2c_generate_evaluation.chapter_diagram.category_context:
        class: i2c\GenerateEvaluationBundle\Services\ChartDataSetConfig\CategoryContext

    i2c_generate_evaluation.chapter_diagram.summary:
        class: i2c\GenerateEvaluationBundle\Services\ChartDataSetConfig\Summary

    i2c_generate_evaluation.chapter_diagram.objective_review:
        class: i2c\GenerateEvaluationBundle\Services\ChartDataSetConfig\ObjectiveReview
