services:
    i2c_generate_evaluation.chart_data_set_config.campaign_background:
        class: i2c\GenerateEvaluationBundle\Services\ChartDataSetConfig\CampaignBackground

    i2c_generate_evaluation.chart_data_set_config.category_context:
        class: i2c\GenerateEvaluationBundle\Services\ChartDataSetConfig\CategoryContext

    i2c_generate_evaluation.chart_data_set_config.summary:
        class: i2c\GenerateEvaluationBundle\Services\ChartDataSetConfig\Summary

    i2c_generate_evaluation.chart_data_set_config.objective_review:
        class: i2c\GenerateEvaluationBundle\Services\ChartDataSetConfig\ObjectiveReview

    i2c_generate_evaluation.chart_data_set_config_services_container:
        class: i2c\GenerateEvaluationBundle\Services\Containers\ChartDataSetConfigContainer
        calls:
          - [addChartDataSetConfigService, [@i2c_generate_evaluation.chart_data_set_config.campaign_background, 'data_set_config_campaign_background']]
          - [addChartDataSetConfigService, [@i2c_generate_evaluation.chart_data_set_config.category_context, 'data_set_config_category_context']]
          - [addChartDataSetConfigService, [@i2c_generate_evaluation.chart_data_set_config.summary, 'data_set_config_summary']]
          - [addChartDataSetConfigService, [@i2c_generate_evaluation.chart_data_set_config.objective_review, 'data_set_config_objective_review']]