parameters:
    raw_tables_config:
        ie_cat_context_data:
            table_name: 'ie_cat_context_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                product: 'VARCHAR(255)'
                metric: 'VARCHAR(255)'
                pp_results: 'DECIMAL(18,6)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_cat_context_data.csv'
            additional_setters: []
        ie_campaign_data:
            table_name: 'ie_campaign_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                campaign_name: 'VARCHAR(255)'
                supplier: 'VARCHAR(255)'
                brand: 'VARCHAR(255)'
                category: 'VARCHAR(255)'
                npd: 'TINYINT'
                media_cost: 'INT(15)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_campaign_data.csv'
        ie_exposed_data:
            table_name: 'ie_exposed_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                media_type: 'VARCHAR(255)'
                exposed: 'INT(15)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_exposed_data.csv'
            additional_setters: []
        ie_media_data:
            table_name: 'ie_media_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                media: 'VARCHAR(255)'
                @start_date: 'DATE'
                @end_date: 'DATE'
                evaluate: 'TINYINT'
                @media_label: 'VARCHAR(255)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_media_data.csv'
            additional_setters:
                - "start_date = STR_TO_DATE(@start_date, '%%d/%%m/%%Y')"
                - "end_date = STR_TO_DATE(@end_date, '%%d/%%m/%%Y')"
                - "media_label = CONCAT(LEFT(media, CHAR_LENGTH(media) - 1), IF(RIGHT(media, 1) REGEXP '[0-9]' = 0, RIGHT(media, 1), ''))"
        ie_offer_data:
            table_name: 'ie_offer_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                sku_name: 'VARCHAR(255)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_offer_data.csv'
            additional_setters: []
        ie_ots_data:
            table_name: 'ie_results_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                media_type: 'VARCHAR(255)'
                obj_priority: 'INT'
                objective: 'VARCHAR(255)'
                metric: 'VARCHAR(255)'
                product: 'VARCHAR(255)'
                timeperiod: 'INT'
                exposed: 'INT(15)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_ots_data.csv'
            additional_setters: []
        ie_promo_data:
            table_name: 'ie_promo_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                @week_commencing: 'DATE'
                product: 'VARCHAR(255)'
                pr_results: 'DECIMAL(18,6)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_promo_data.csv'
            additional_setters:
                - "week_commencing = STR_TO_DATE(@week_commencing, '%%d/%%m/%%Y')"
        ie_results_data:
            table_name: 'ie_results_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                media_type: 'VARCHAR(255)'
                obj_priority: 'INT'
                objective: 'VARCHAR(255)'
                metric: 'VARCHAR(255)'
                product: 'VARCHAR(255)'
                timeperiod: 'INT'
                exposed: 'INT(15)'
                control: 'DECIMAL(18,6)'
                uplift: 'DECIMAL(18,6)'
                pct_uplift: 'DECIMAL(18,6)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_results_data.csv'
            additional_setters: []
        ie_timings_data:
            table_name: 'ie_timings_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                period: 'INT'
                @period_date: 'DATE'
            primary_key: 'master_campaign_id'
            file_name: 'ie_timings_data.csv'
            additional_setters:
                - "period_date = STR_TO_DATE(@period_date, '%%d/%%m/%%Y')"
        ie_weekly_results_data:
            table_name: 'ie_weekly_results_data'
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                @week_commencing: 'DATE'
                product: 'VARCHAR(255)'
                metric: 'VARCHAR(255)'
                exposed: 'DECIMAL(18,2)'
                control: 'DECIMAL(18,6)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_weekly_results_data.csv'
            additional_setters:
                - "week_commencing = STR_TO_DATE(@week_commencing, '%%d/%%m/%%Y')"

    media_laydown_config:
        - { color: "#ccc", media: ['Instore Sampling', 'Entrance Gates', 'Six Sheets'], label: 'Evaluated media' }
        - { color: "#555", media: ['TV Wall', 'JS Magazine'], label: 'In-Store Promotions' }
