imports:
    - { resource: 'config.yml' }
    - { resource: 'extract_services.yml'}
    - { resource: 'chart_data_set_config_services.yml'}
    - { resource: 'import_config.yml' }

services:
    i2c_generate_evaluation.import_all:
        class: i2c\GenerateEvaluationBundle\Command\ImportCommand
        arguments: [%import%,@monolog.logger, @i2c_generate.import_all]
        tags:
            - { name: console.command }

    i2c_generate_evaluation.raw_import:
        class: i2c\GenerateEvaluationBundle\Command\RawImportCommand
        arguments: [%raw_tables_config%, %import_validation_filename%, @monolog.logger]
        tags:
            - { name: console.command }

    i2c_generate_evaluation.evaluation_generate_command:
        class: i2c\GenerateEvaluationBundle\Command\GenerateEvaluationsCommand
        arguments: [@i2c_generate_evaluation.evaluation_generate_service, %evaluation_templates_folder_path%, @i2c_generate_evaluation.extract_cids, @monolog.logger]
        tags:
            - { name: console.command }

    i2c_generate_evaluation.twig_minify_command:
        class: i2c\GenerateEvaluationBundle\Command\MinifyTwigCommand
        tags:
            - { name: console.command }

    i2c_generate_evaluation.evaluation_generate_service:
        class: i2c\GenerateEvaluationBundle\Services\GenerateEvaluations
        arguments: [@templating.engine.twig, @doctrine.orm.default_entity_manager, @serializer, 'i2cGenerateEvaluationBundle', @i2c_generate_evaluation.chart_data_set_generate_service]
        calls:
          - [setExtractContainer, [@i2c_generate_evaluation.extract_services_container]]
          - [setChartDataSetConfigContainer, [@i2c_generate_evaluation.chart_data_set_config_services_container]]
          - [setOptionalChaptersConfigService, [@i2c_generate_evaluation.optional_chapters_config_service]]

    i2c_generate_evaluation.chart_data_set_generate_service:
        class: i2c\GenerateEvaluationBundle\Services\GenerateChartDataSet
        arguments: [@templating.engine.twig, @doctrine.orm.default_entity_manager, @serializer]
        calls:
          - [setChartDataSetContainer, [@i2c_generate_evaluation.chart_data_set_services_container]]

    i2c_generate_evaluation.import_data:
        class: i2c\GenerateEvaluationBundle\Services\ImportData
        calls:
            - [buildPdoConnection, [%database_host%, %database_user%, %database_password%, %database_name%]]

    i2c_generate_evaluation.extract_cids:
        class: i2c\GenerateEvaluationBundle\Services\ExtractCids
        arguments: [@doctrine.dbal.default_connection]

    i2c_generate_evaluation.optional_chapters_config_service:
        class: i2c\GenerateEvaluationBundle\Services\OptionalChaptersConfig
        arguments: [@doctrine.dbal.default_connection]

    i2c_generate.import_all:
        class: i2c\GenerateEvaluationBundle\Services\ImportAll
        calls:
            - [buildPdoConnection, [%database_host%, %database_user%, %database_password%, %database_name%]]
