imports:
    - { resource: 'config.yml' }
services:
    i2c_generate_evaluation.raw_import:
        class: i2c\GenerateEvaluationBundle\Command\RawImportCommand
        arguments: [%raw_tables_config%]
        tags:
            - { name: console.command }

    i2c_generate_evaluation.evaluation_generate:
        class: i2c\GenerateEvaluationBundle\Command\GenerateEvaluationsCommand
        arguments: [%media_laydown_colors%]
        tags:
            - { name: console.command }

    i2c_generate_evaluation.campaign_objective_data:
        class: i2c\GenerateEvaluationBundle\Services\CampaignObjectiveDataService
        arguments: [@doctrine]
