imports:
    - { resource: 'config.yml' }
    - { resource: 'extract_services.yml'}
    - { resource: 'chapter_diagram_services.yml'}

services:
    i2c_generate_evaluation.raw_import:
        class: i2c\GenerateEvaluationBundle\Command\RawImportCommand
        arguments: [%raw_tables_config%, @monolog.logger]
        tags:
            - { name: console.command }

    i2c_generate_evaluation.evaluation_generate_command:
        class: i2c\GenerateEvaluationBundle\Command\GenerateEvaluationsCommand
        arguments: [@i2c_generate_evaluation.evaluation_generate_service, %evaluation_templates_folder_path%, @i2c_generate_evaluation.extract_cids, @monolog.logger]
        tags:
            - { name: console.command }

    i2c_generate_evaluation.evaluation_generate_service:
        class: i2c\GenerateEvaluationBundle\Services\GenerateEvaluations
        arguments: [@templating.engine.twig, @doctrine.orm.default_entity_manager, @serializer, "i2cGenerateEvaluationBundle", @i2c_generate_evaluation.table_data_generate_service]
        calls:
          - [addExtractService, [@i2c_generate_evaluation.extract_evaluation, "extract_evaluation"]]
          - [addExtractService, [@i2c_generate_evaluation.extract_evaluation_channels, "extract_evaluation_channels"]]
          - [addExtractService, [@i2c_generate_evaluation.extract_evaluation_campaign_objectives, "extract_evaluation_campaign_objectives"]]
          - [addExtractService, [@i2c_generate_evaluation.extract_campaign_background, "extract_campaign_background"]]
          - [addExtractService, [@i2c_generate_evaluation.extract_category_context, "extract_category_context"]]
          - [addExtractService, [@i2c_generate_evaluation.extract_objective_review, "extract_objective_review"]]
          - [addExtractService, [@i2c_generate_evaluation.extract_sampling_performance, "extract_sampling_performance"]]
          - [addExtractService, [@i2c_generate_evaluation.extract_summary, "extract_summary"]]

    i2c_generate_evaluation.table_data_generate_service:
        class: i2c\GenerateEvaluationBundle\Services\GenerateTableData
        arguments: [@templating.engine.twig, @doctrine.orm.default_entity_manager, @serializer]
        calls:
          - [addExtractService, [@i2c_generate_evaluation.extract_table_data_category_context_promotional_activity, "extract_table_data_promotional_activity"]]
          - [addExtractService, [@i2c_generate_evaluation.extract_table_data_category_context_sales_performance, "extract_table_data_sales_performance"]]

    i2c_generate_evaluation.import_data:
        class: i2c\GenerateEvaluationBundle\Services\ImportData
        calls:
            - [buildPdoConnection, [%database_host%, %database_user%, %database_password%, %database_name%]]

    i2c_generate_evaluation.extract_cids:
        class: i2c\GenerateEvaluationBundle\Services\ExtractCids
        arguments: [@doctrine.dbal.connection]

    i2c_generate_evaluation.extract_services_container:
        class:
