evaluation_evaluation.get_evaluations_by_id_minimal:
    path: /api/evaluations
    methods: [GET]
    defaults: { _controller: EvaluationEvaluationBundle:Evaluation:getEvaluationsByIdMinimal }

evaluation_evaluation.get_evaluation_by_id:
    path: /api/evaluations/{evaluationUid}
    methods: [GET]
    defaults: { _controller: EvaluationEvaluationBundle:Evaluation:getEvaluationById }

evaluation_evaluation.publish_evaluation:
    path: /api/evaluations/{evaluationUid}/publish
    methods: [POST]
    defaults: { _controller: EvaluationEvaluationBundle:Evaluation:markEvaluationAsPublished }

evaluation_evaluation.unpublish_evaluation:
    path: /api/evaluations/{evaluationUid}/unpublish
    methods: [POST]
    defaults: { _controller: EvaluationEvaluationBundle:Evaluation:markEvaluationAsDraft }

evaluation_evaluation.get_evaluation_chapter_by_id:
    path: /api/evaluations/{evaluationUid}/chapters/{chapterId}
    methods: [GET]
    defaults: { _controller: EvaluationEvaluationBundle:Evaluation:getChapterById }

evaluation_evaluation.update_evaluation_chapter:
    path: /api/evaluations/{evaluationUid}/chapters/{chapterUid}
    methods: [POST]
    defaults: { _controller: EvaluationEvaluationBundle:Evaluation:updateChapter }