php_memory_limit: "3G"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"

php_packages:
  - php56-php
  - php56-php-cli
  - php56-php-common
  - php56-php-devel.x86_64
  - php56-php-gd
  - php56-php-mbstring
  - php56-php-pdo
#  - php-pecl-apc
  - php56-php-xml
  - php56-php-intl
  - php56-php-soap
  - php56-php-mcrypt
  - php56-php-posix
  - php56-php-pecl-apc
  - php56-php-mysql

#mysql_packages:
#  - mariadb
#  - mariadb-server
#  - mariadb-libs
#  - MySQL-python
#  - perl-DBD-MySQL
mysql_daemon: mysql
mysql_root_password: root
mysql_root_password_update: yes
mysql_socket: /var/lib/mysql/mysql.sock
mysql_log_error: /var/log/mysql.log
#mysql_syslog_tag: mariadb
mysql_pid_file: /var/lib/mysql/mysql.pid
mariadb_version: 5.5
#mysql_enablerepo: "mariadb"

composer_path: /usr/local/bin/composer
composer_keep_updated: true
composer_add_to_path: true
composer_github_oauth_token: 'f41d1264849cb0098970a887aa040d534b0a1085'
php_executable: php56
php_conf_path: /opt/remi/php56/root/etc/


# Jailed user variables

sftp_user:
  - name: sftp-user
    password: '$6$rounds=656000$dHJdvzXneg3GTE0r$gyRPu1ytc70NrvnCcykqKzhsVw1ilw8QSWbgEWIeqsxgzaLYquFh1bH2eKd1csGVF8qKzp4wOmo6JnU5lOMxO.' # Le7gmeuy4qvA
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChPbLtYmEjEVruL/4x0F8/3ysgdCfUvD1wIGl4ue0/JlQ9dERNmMOQdg5OIWKc+cXWVffCC2V+i8oJMIdh20hX7KAjaZ69756qivCp0D/JNZ07HowRAUSrPS3jAvKMsg/ekV/lZcE5QVHMgoGMIT53AzL/irjFa2SDbf1jtBu7SlExerI8auwqhtrFuIy8h9ephUlpBhAPBWZRc2sRp3wiKR0ZGAVY0eFBjikXkMIFDtmEgVpJCErbNk8Ax/OEBZnJb7u/yoOg/VtUnftIU/K1qwgZXymsE7GXfnWFQpX12O4xCbakYrHrUe3a6X9nZG8+hcWvxaxdKcNDVRZVnaHh zoltan.sandor@Admins-MacBook-Pro.local'
    folder: '/sftp-folder'
