php_memory_limit: "3G"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-gd
  - php-mbstring
  - php-pdo
#  - php-pecl-apc
  - php-xml
  - php-intl
  - php-soap
  - php-mcrypt
  - php-posix
  - php-pecl-apc
  - php-mysql

mysql_packages:
  - mysql
  - mysql-server
  - mysql-libs
  - MySQL-python
  - perl-DBD-MySQL
mysql_root_password: ""
mysql_root_password_update: yes
mysql_enabled_on_startup: yes
mysql_daemon: mysqld
mysql_socket: /var/lib/mysql/mysql.sock
mysql_log_error: /var/log/mysqld.log
mysql_syslog_tag: mysqld
# mysql_pid_file: /var/run/mysql/mysql.pid

composer_path: /usr/local/bin/composer
composer_keep_updated: true
composer_add_to_path: true
composer_github_oauth_token: 'f41d1264849cb0098970a887aa040d534b0a1085'
php_executable: php
