services:
    i2c_generate_pdf.evaluation_queue_service:
        class: i2c\GeneratePdfBundle\Services\EvaluationQueue
        arguments: [@doctrine.dbal.default_connection]

    i2c_generate_pdf.generate_evaluation_pdf_service:
        class: i2c\GeneratePdfBundle\Services\GenerateEvaluationPdf