parameters:
    raw_tables_config:
        ie_cat_context_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                product: 'VARCHAR(255)'
                metric: 'VARCHAR(255)'
                pp_results: 'DECIMAL(18,6)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_cat_context_data.csv'
        ie_campaign_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                campaign_name: 'VARCHAR(255)'
                supplier: 'VARCHAR(255)'
                brand: 'VARCHAR(255)'
                category: 'VARCHAR(255)'
                npd: 'TINYINT'
                media_cost: 'INT(15)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_campaign_data.csv'
        ie_exposed_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                media_type: 'VARCHAR(255)'
                exposed: 'INT(15)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_exposed_data.csv'
        ie_media_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                media: 'VARCHAR(255)'
                # todo refactor this to mysql DATE type
                start_date: 'VARCHAR(10)'
                # todo refactor this to mysql DATE type
                end_date: 'VARCHAR(10)'
                evaluate: 'TINYINT'
            primary_key: 'master_campaign_id'
            file_name: 'ie_media_data.csv'
        ie_offer_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                sku_name: 'VARCHAR(255)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_offer_data.csv'
        ie_ots_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                media_type: 'VARCHAR(255)'
                obj_priority: 'INT'
                objective: 'VARCHAR(255)'
                metric: 'VARCHAR(255)'
                product: 'VARCHAR(255)'
                timeperiod: 'INT'
                exposed: 'INT(15)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_ots_data.csv'
        ie_promo_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                # todo refactor this to mysql DATE type
                week_commencing: 'VARCHAR(10)'
                product: 'VARCHAR(255)'
                pr_results: 'DECIMAL(18,6)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_promo_data.csv'
        ie_results_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                media_type: 'VARCHAR(255)'
                obj_priority: 'INT'
                objective: 'VARCHAR(255)'
                metric: 'VARCHAR(255)'
                product: 'VARCHAR(255)'
                timeperiod: 'INT'
                exposed: 'INT(15)'
                control: 'DECIMAL(18,6)'
                uplift: 'DECIMAL(18,6)'
                pct_uplift: 'DECIMAL(18,6)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_results_data.csv'
        ie_timings_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                period: 'INT'
                # todo refactor this to mysql DATE type
                period_date: 'VARCHAR(10)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_timings_data.csv'
        ie_weekly_results_data:
            columns:
                master_campaign_id: 'VARCHAR(255) NOT NULL'
                # todo refactor this to mysql DATE type
                week_commencing: 'VARCHAR(10)'
                product: 'VARCHAR(255)'
                metric: 'VARCHAR(255)'
                exposed: 'INT(15)'
                control: 'DECIMAL(18,6)'
            primary_key: 'master_campaign_id'
            file_name: 'ie_weekly_results_data.csv'

services:
    i2c_evaluation.raw_import:
        class: i2c\EvaluationBundle\Command\RawImportCommand
        arguments: [%raw_tables_config%]
        tags:
            - { name: console.command }
