i2c_evaluation.get_evaluations_by_cid_minimal:
    path: /api/evaluations
    methods: [POST]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:getEvaluationsByCidMinimal }

i2c_evaluation.get_evaluation_by_cid:
    path: /api/evaluations/{evaluationCid}
    methods: [GET]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:getEvaluationByCid }

i2c_evaluation.get_table_data:
    path: /api/evaluations/{evaluationCid}/dataset/{tableDataId}
    methods: [GET]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:getTableData }

i2c_evaluation.publish_evaluation:
    path: /api/evaluations/{evaluationCid}/publish
    methods: [POST]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:markEvaluationAsPublished }

i2c_evaluation.unpublish_evaluation:
    path: /api/evaluations/{evaluationCid}/unpublish
    methods: [POST]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:markEvaluationAsDraft }

i2c_evaluation.get_evaluation_chapter_by_id:
    path: /api/evaluations/{evaluationCid}/chapters/{chapterId}
    methods: [GET]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:getChapterById }

i2c_evaluation.get_permanent_evaluation_pdf:
    path: /api/evaluations/{evaluationCid}/pdf
    methods: [GET]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:getPdf }

i2c_evaluation.get_temporary_evaluation_pdf:
    path: /api/evaluations/{evaluationCid}/pdf/temporary
    methods: [GET, HEAD]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:getTemporaryPdf }

i2c_evaluation.generate_evaluation_pdf:
    path: /api/pdf/{evaluationCid}/temporary
    methods: [POST]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:generateTemporaryPdf }

i2c_evaluation.mark_pdf_as_permanent:
    path: /api/pdf/permanent/{evaluationCid}
    methods: [POST]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:markPdfAsPermanent }

i2c_evaluation.mark_pdf_as_permanent_with_publish:
    path: /api/pdf/permanent/{evaluationCid}/publish
    methods: [POST]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:markPdfAsPermanentWithPublish }

i2c_evaluation.update_evaluation_chapter:
    path: /api/evaluations/{evaluationCid}/chapters/{chapterId}
    methods: [POST]
    defaults: { _controller: i2cEvaluationBundle:Api/Evaluation:updateChapter }