---
- hosts: jenkins

  tasks:
  - name: Fetch Jenkins repo
    command: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo"

  - name: Import Jenkins repo
    command: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"

  - name: Install Jenkins
    yum: pkg={{ item }} state=present
    with_items:
      - jenkins

  - name: Install dependencies
    yum: pkg={{ item }} state=present
    with_items:
      - java
      - vim
      - man
      - tree
      - curl
      - wget
      - unzip
      - mlocate
      - git
      - bind-utils
      - traceroute

  - name: Install Vagrant
    yum: name=https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.rpm state=present

  - name: Grab i2c repo
    git: repo=git@github.com:RelyConsultancy/i2ces.git
      dest=/root/i2ces
      accept_hostkey=true
