---
- hosts: all
  remote_user: root
  vars_files:
    - vars/main.yml
    - vars/server_parameters_qa.yml # Replace with your own

  roles:
    - init
    - jailed-users
    - { role: phantomjs, sudo: yes, tags: phantomjs}
    - { role: pdfunite, sudo: yes, tags: pdfunite}
    - geerlingguy.repo-remi
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.composer
    - oro
