---
- hosts: all
  remote_user: root
  vars_files:
    - vars/main.yml
    - vars/server_parameters_dev.yml # Replace with your own

  roles:
    - { role: init, tags: init}
    - { role: jailed-users, tags: jailed-users}
    - { role: phantomjs, sudo: yes, tags: phantomjs}
    - { role: pdfunite, sudo: yes, tags: pdfunite}
    - { role: repo-remi, tags: remi}
    - { role: mysql, tags: mysql}
    - { role: apache, tags: apache}
    - { role: php, tags: php}
    - { role: sync, tags: sync}
    - { role: composer, tags: composer}
    - { role: oro, tags: oro}
    - { role: cron, tags: cron}
