---
- hosts: all
  remote_user: root
  vars_files:
    - vars/main.yml

  roles:
    - init
    - jailed-users
    - geerlingguy.repo-remi
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.composer
    - oro
