i2c_page.get_page_by_type:
    path: /api/pages/{type}
    methods: [GET]
    defaults: { _controller: i2cPageBundle:Api/Page:getPageContent }

i2c_page.update_page:
    path: /api/pages/{type}
    methods: [POST]
    defaults: { _controller: i2cPageBundle:Api/Page:updatePage }
