parameters:
    initial_setup_config:
        roles:
            supplier:
                name: User
                new_name: Supplier
                access:
                    evaluation:
                        oid: 'Entity:i2cEvaluationBundle:Evaluation'
                        permissions: [64] # EntityMaskBuilder::MASK_VIEW_LOCAL, EntityMaskBuilder::MASK_EDIT_LOCAL
                    page:
                        oid: 'Entity:i2cPageBundle:Page'
                        permissions: [64] # EntityMaskBuilder::MASK_VIEW_LOCAL, EntityMaskBuilder::MASK_EDIT_LOCAL
                    groups:
                        oid: 'Entity:OroUserBundle:Group'
                        permissions: [0] # EntityMaskBuilder::MASK_VIEW_LOCAL, EntityMaskBuilder::MASK_EDIT_LOCAL
            account_manager:
                name: Manager
                new_name: Account Manager
                identifier: ROLE_ACCOUNT_MANAGER
                access:
                    evaluation:
                        oid: 'Entity:i2cEvaluationBundle:Evaluation'
                        permissions: [64, 256] # EntityMaskBuilder::MASK_VIEW_LOCAL, EntityMaskBuilder::MASK_EDIT_LOCAL
                    page:
                        oid: 'Entity:i2cPageBundle:Page'
                        permissions: [64, 256] # EntityMaskBuilder::MASK_VIEW_LOCAL, EntityMaskBuilder::MASK_EDIT_LOCAL
                    groups:
                        oid: 'Entity:OroUserBundle:Group'
                        permissions: [0] # EntityMaskBuilder::MASK_VIEW_LOCAL, EntityMaskBuilder::MASK_EDIT_LOCAL
                    business_unit:
                        oid: 'Entity:OroOrganizationBundle:BusinessUnit'
                        permissions: [16777216, 33554432, 67108864, 134217728, 268435456] # Full system access
                    supplier:
                        oid: 'Entity:i2cSupplierBundle:Supplier'
                        permissions: [16777216, 33554432, 67108864, 134217728, 268435456] # Full system access
                    user:
                        oid: 'Entity:OroUserBundle:User'
                        permissions: [16777216, 33554432, 67108864, 134217728, 268435456] # Full system access
                    organization:
                        oid: 'Entity:OroOrganizationBundle:Organization'
                        permissions: [16777216, 33554432, 67108864, 134217728] # Full system access with no assign
                    attachment:
                        oid: 'Entity:OroAttachmentBundle:Attachment'
                        permissions: [16777216, 33554432, 67108864, 134217728, 268435456] # Full system access