imports:
    - { resource: 'initial_dummy_data.yml' }
services:
    i2c_setup.initial_setup_command:
        class: i2c\SetupBundle\Command\InitialSetupCommand
        arguments: [%initial_setup_config%, @oro_user.manager]
        tags:
          - { name: console.command }

    i2c_setup.schema_update_command:
        class: i2c\SetupBundle\Command\DatabaseSchemaUpdateCommand
        arguments: [@i2c_setup.schema_update_service, @monolog.logger]
        tags:
          - { name: console.command }

    i2c_setup.schema_update_service:
        class: i2c\SetupBundle\Services\SchemaUpdate
        arguments: [@doctrine.dbal.default_connection, %migration_sql_folder_path%]
