imports:
    - { resource: 'initial_setup_config.yml' }
services:
    i2c_setup.initial_setup_command:
        class: i2c\SetupBundle\Command\InitialSetupCommand
        arguments: [%initial_setup_config%, @oro_user.manager]
        tags:
          - { name: console.command }

    i2c_setup.schema_update_command:
        class: i2c\SetupBundle\Command\DatabaseSchemaUpdateCommand
        arguments: [@i2c_setup.schema_update_container]
        tags:
          - { name: console.command }

    i2c_setup.schema_update_container:
        class: i2c\SetupBundle\Services\SchemaUpdateContainer
        calls:
          - [ addSchemaUpdateService, [@evaluation_evaluation.evaluation_schema_update] ]
          - [ addSchemaUpdateService, [@evaluation_evaluation.chapter_schema_update] ]
          - [ addSchemaUpdateService, [@evaluation_evaluation.evaluation_chapters_schema_update] ]
